import { useState, useContext } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";

import { AppContext } from "app/context";
import Button from "app/components/Button";
import styles from "styles/Home.module.css";

const DetailInput = styled.textarea`
  border: 1px solid #ccc;
  border-radius: 5px;
  width: 400px;
  height: 300px;
  padding: 10px;
  font-size: 15px;
  color: #666;
  &:focus {
    outline: none;
    box-shadow: none;
  }
`;

const StyledSection = styled.div`
  width: 400px;
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const Details = () => {
  const {
    query: { id },
  } = useRouter();
  const { details, handleOnUpdateDetail } = useContext(AppContext);
  const [note, setNote] = useState(details[id] || "");

  const handleOnSave = () => handleOnUpdateDetail(id, note);

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>{id}</h2>
        <StyledSection>
          <p>Note</p>
          <Button
            onClick={handleOnSave}
            disabled={note === details[id]}
            type="button"
          >
            {note === details[id] ? "Saved" : "Save"}
          </Button>
        </StyledSection>
        <DetailInput value={note} onChange={(e) => setNote(e.target.value)} />
      </main>
    </div>
  );
};

export default Details;
